// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWijDvKQEfMX2QGRFg2_bFWp-fFmFCTs',
    appId: '1:766237521079:web:d15c567fac191646cdc932',
    messagingSenderId: '766237521079',
    projectId: 'offline-notes-sync',
    authDomain: 'offline-notes-sync.firebaseapp.com',
    storageBucket: 'offline-notes-sync.firebasestorage.app',
    measurementId: 'G-ZKC4J715P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqiBmuJ9Tr1w98NmaUEmH6yqAAaxc7pI',
    appId: '1:766237521079:android:4937eb56f8cda7b8cdc932',
    messagingSenderId: '766237521079',
    projectId: 'offline-notes-sync',
    storageBucket: 'offline-notes-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEyQe5KM832FI5R9UC5rIaahxBD3q2hRc',
    appId: '1:766237521079:ios:18bceb67384028dbcdc932',
    messagingSenderId: '766237521079',
    projectId: 'offline-notes-sync',
    storageBucket: 'offline-notes-sync.firebasestorage.app',
    iosBundleId: 'com.example.offlineNotesSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEyQe5KM832FI5R9UC5rIaahxBD3q2hRc',
    appId: '1:766237521079:ios:18bceb67384028dbcdc932',
    messagingSenderId: '766237521079',
    projectId: 'offline-notes-sync',
    storageBucket: 'offline-notes-sync.firebasestorage.app',
    iosBundleId: 'com.example.offlineNotesSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWWijDvKQEfMX2QGRFg2_bFWp-fFmFCTs',
    appId: '1:766237521079:web:669fe0ef3bd26f0ccdc932',
    messagingSenderId: '766237521079',
    projectId: 'offline-notes-sync',
    authDomain: 'offline-notes-sync.firebaseapp.com',
    storageBucket: 'offline-notes-sync.firebasestorage.app',
    measurementId: 'G-FHR1PE341K',
  );
}
